# https://taskfile.dev

version: "3"

vars:
  AWS_PROFILE: logik-dev
  REGISTRY_URI: 847186409068.dkr.ecr.eu-west-1.amazonaws.com/logik-dev
  FUNCTION_NAME: logik-graphql-dev
  API_PORT: 8000
  DB_PORT: 8001
  ARCHITECTURE: arm64
  PLATFORM: "linux/{{.ARCHITECTURE}}"
  IMAGE_TAG: "{{.REGISTRY_URI}}:{{.FUNCTION_NAME}}-{{.ARCHITECTURE}}"

dotenv: [".env"]

tasks:
  default:
    deps: [install]
    cmds:
      - python -m api.app
    env:
      POWERTOOLS_SERVICE_NAME: logik-api
      SECRET_KEY: 123456abcdef

  install:
    desc: Installs all dependencies
    deps: [python:poetry]

  python:virtualenv:
    desc: Creates a Python virtualenv for the project
    cmds:
      - python -m venv .venv
    status:
      - test -d .venv

  python:poetry:
    desc: Installs Python dependencies via Poetry package manager
    deps: [python:virtualenv]
    preconditions:
      - sh: command -v poetry
        msg: "Make sure Poetry is installed"
    cmds:
      - poetry install --no-root
    sources:
      - pyproject.toml
      - poetry.lock

  db:
    desc: Run DDB locally using docker
    cmds:
      - docker run -p {{.DB_PORT}}:{{.DB_PORT}} amazon/dynamodb-local -jar DynamoDBLocal.jar -port {{.DB_PORT}}

  build:
    desc: Builds the Docker image to be used by AWS Lambda locally
    cmds:
      - >
        docker build .
        -t {{.IMAGE_TAG}}
        -f Dockerfile
        --platform {{.PLATFORM}}
        --compress
      # - >
      #   docker buildx build .
      #   --platform {{.PLATFORM}}
      #   --tag {{.IMAGE_TAG}}
      #   --push

  push:
    desc: Pushes the API onto AWS ECR
    deps: [build]
    cmds:
      - aws --profile {{.AWS_PROFILE}} ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin {{.REGISTRY_URI}}
      - docker push {{.IMAGE_TAG}}
      - aws --profile {{.AWS_PROFILE}} lambda update-function-code --function-name {{.FUNCTION_NAME}} --image-uri {{.IMAGE_TAG}} > /dev/null

  invoke:
    desc: Invokes the deployed Lambda function
    cmds:
      - >
        aws --profile {{.AWS_PROFILE}} lambda invoke
        --function-name {{.FUNCTION_NAME}}
        --payload fileb://events/login.json
        /dev/stdout

  tail:
    desc: Tails the logs of the deployed Lambda function
    cmds:
      - aws --profile {{.AWS_PROFILE}} logs tail /aws/lambda/{{.FUNCTION_NAME}} --follow

  explore:
    desc: Runs a shell inside of the Lambda's Docker image
    deps: [build]
    cmds:
      - docker run -it --rm --platform {{.PLATFORM}} --entrypoint /bin/bash {{.IMAGE_TAG}}

  run:
    desc: Runs the Lambda service locally using the Runtime Interface Emulator (RIE)
    deps: [build]
    cmds:
      - >
        docker run -it --rm
        --publish {{.API_PORT}}:8080
        --env SECRET_KEY=123456abcdef
        --platform {{.PLATFORM}}
        {{.IMAGE_TAG}}

  emulate:
    desc: Sends a payload against a local Lambda
    cmds:
      # - curl -XPOST "http://localhost:{{.API_PORT}}/2015-03-31/functions/function/invocations" -d @events/homepage.json
      - curl -XPOST "http://localhost:{{.API_PORT}}/2015-03-31/functions/function/invocations" -d @events/login.json
      - curl -XPOST "http://localhost:{{.API_PORT}}/2015-03-31/functions/function/invocations" -d @events/article.json
